### ISSUE TITLE
[DOCS-168] Feedback on "Issues page"

### ISSUE THREAD

**Issue by madalenamelo** [codacy/docs#771] opened 2021-08-06 15:19 UTC
**Type of feedback**
-   [ ] Bug or incorrect information
-   [x] Missing information
-   [ ] Outdated information
-   [ ] Enhancement
-   [ ] Other

**Feedback**

**Affected pages**
This feedback applies to the following documentation pages / URLs:

https://docs.codacy.com/repositories/issues/
https://docs.codacy.com/repositories/commits/#commits-page

**Additional context**
If applicable, provide any other context or information that could be useful in updating the documentation:

The "possible new issues" and "possible fixed issues" are not mentioned in the documentation. These concepts are different from the New issues and Fixed issues and are not reported in the commits list but if you open the commit you can expand them and see a list of issues under the relevant tab (I made a Loom video to illustrate [here](https://www.loom.com/share/5b3871361b91482a864b648fb4993622))

**Comment by prcr** [comment] 2021-08-06 15:51
Duplicate of https://github.com/codacy/docs/issues/143.

**Comment by prcr** [comment] 2021-08-13 16:16
I'm closing this issue after having copied the feedback to #143:

https://github.com/codacy/docs/issues/143#issuecomment-898573321

**Closed by prcr** 2021-08-13 16:16 UTC
Labels: missing info
