### ISSUE TITLE
[DOCS-247] Add info on how Codacy manages Branches by default 

### ISSUE THREAD

**Issue by IGFCoimbra** [codacy/docs#627] opened 2021-04-20 15:54 UTC
**Type of feedback**
-   [ ] Bug or incorrect information
-   [X] Missing information
-   [ ] Outdated information
-   [ ] Enhancement
-   [ ] Other

**Feedback**

We don't have info regarding Codacy's normal behavior regarding branches. When they are enabled, when they are disabled, which one is the main, etc. 

**Affected pages**
This feedback applies to the following documentation pages / URLs:

https://docs.codacy.com/repositories-configure/managing-branches/

**Additional context**
If applicable, provide any other context or information that could be useful in updating the documentation:

**Comment by prcr** [comment] 2021-04-21 12:47
Duplicate of https://github.com/codacy/docs/issues/179, I'm closing this issue since the other one already includes more information and I'll add a note there saying that the information was necessary again. :+1:

**Closed by prcr** 2021-04-21 12:47 UTC
Labels: missing info
